In [1]:
import numpy as np
import pandas as pd
arr=np.array([10,20,30,40,50])
print("Array:",arr)
print("Mean:",arr.mean())
print("Reshaped 2D:\n",arr.reshape(5,1))
print("Sliced(index 1 to 3):",arr[1:4])
#------Creating a dataframe----
data={"Name":['Asha',"Ravi","Meera","Karan"],
      "Marks":[88,72,91,65],
      "Branch":["CSE","ECE","CSE","ISE"]
     }
df =pd.DataFrame(data)
print(df)
#---Indexing and Slicing---
print("\nFirst2 rows:\n",df.iloc[0:2])
print("\nMarks and branch column:",df["Marks"],df["Branch"])
#print("\nBranch column:\n",df["Branch"])
print("\nRows where Marks>70:\n",df[df["Marks"]>70])

Array: [10 20 30 40 50]
Mean: 30.0
Reshaped 2D:
 [[10]
 [20]
 [30]
 [40]
 [50]]
Sliced(index 1 to 3): [20 30 40]
    Name  Marks Branch
0   Asha     88    CSE
1   Ravi     72    ECE
2  Meera     91    CSE
3  Karan     65    ISE

First2 rows:
    Name  Marks Branch
0  Asha     88    CSE
1  Ravi     72    ECE

Marks and branch column: 0    88
1    72
2    91
3    65
Name: Marks, dtype: int64 0    CSE
1    ECE
2    CSE
3    ISE
Name: Branch, dtype: str

Rows where Marks>70:
     Name  Marks Branch
0   Asha     88    CSE
1   Ravi     72    ECE
2  Meera     91    CSE

In [15]:
import pandas as pd
df = pd.read_csv (r"C:\Users\user\Downloads\student_exam_performance.csv")
df.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [16]:
df.head()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [17]:
df.tail()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [18]:
df.shape

(100000, 44)

In [19]:
df.columns

Index(['student_id', 'age', 'gender', 'education_level', 'school_type',
       'family_income', 'parent_education', 'urban_rural',
       'previous_exam_score', 'previous_gpa', 'attendance_percentage',
       'assignment_completion_rate', 'class_participation',
       'study_hours_per_day', 'self_study_hours', 'private_tuition',
       'online_learning_hours', 'study_consistency', 'study_environment',
       'study_method', 'revision_frequency', 'practice_tests_completed',
       'notes_quality', 'sleep_hours', 'sleep_quality', 'daily_screen_time',
       'physical_activity_hours', 'break_frequency', 'stress_level',
       'motivation_level', 'internet_access', 'device_availability',
       'educational_app_usage', 'online_course_hours', 'exam_difficulty',
       'exam_preparation_days', 'questions_attempted', 'questions_correct',
       'time_management_score', 'exam_anxiety_level', 'exam_score',
       'performance_grade', 'pass_status', 'performance_level'],
      dtype='str')

In [20]:
df.dtypes

student_id                        str
age                             int64
gender                            str
education_level                   str
school_type                       str
family_income                     str
parent_education                  str
urban_rural                       str
previous_exam_score           float64
previous_gpa                  float64
attendance_percentage         float64
assignment_completion_rate    float64
class_participation               str
study_hours_per_day           float64
self_study_hours              float64
private_tuition                 int64
online_learning_hours         float64
study_consistency                 str
study_environment                 str
study_method                      str
revision_frequency                str
practice_tests_completed        int64
notes_quality                     str
sleep_hours                   float64
sleep_quality                     str
daily_screen_time             float64
physical_activity_hours       float64
break_frequency                   str
stress_level                    int64
motivation_level                  str
internet_access                 int64
device_availability               str
educational_app_usage             str
online_course_hours           float64
exam_difficulty                   str
exam_preparation_days           int64
questions_attempted             int64
questions_correct               int64
time_management_score         float64
exam_anxiety_level            float64
exam_score                    float64
performance_grade                 str
pass_status                       str
performance_level                 str
dtype: object

In [21]:
df.info

<bound method DataFrame.info of        student_id  age  gender education_level school_type family_income  \
0      STU_000001   20  Female     High School      Public        Middle
1      STU_000002   17    Male     High School      Public        Middle
2      STU_000003   18   Other   Undergraduate      Public        Middle
3      STU_000004   20    Male     High School      Public        Middle
4      STU_000005   16  Female     High School     Private          High
...           ...  ...     ...             ...         ...           ...
99995  STU_099996   17    Male   Undergraduate      Public  Upper-Middle
99996  STU_099997   14  Female     High School      Public  Upper-Middle
99997  STU_099998   16  Female     High School      Public  Upper-Middle
99998  STU_099999   15  Female     High School     Private          High
99999  STU_100000   18  Female   Undergraduate     Charter  Lower-Middle

      parent_education urban_rural  previous_exam_score  previous_gpa  ...  \
0                  NaN       Rural                78.36          2.95  ...
1                  NaN    Suburban                73.40          2.89  ...
2               Master       Urban                82.76          3.35  ...
3          High School    Suburban                60.61          2.57  ...
4             Bachelor    Suburban                74.79          2.84  ...
...                ...         ...                  ...           ...  ...
99995              NaN    Suburban                78.73           NaN  ...
99996         Bachelor    Suburban                75.70          2.98  ...
99997      High School    Suburban                84.69          3.27  ...
99998           Master       Rural                74.70          3.06  ...
99999              NaN       Urban                76.73          2.97  ...

       exam_difficulty  exam_preparation_days questions_attempted  \
0               Medium                     27                  95
1                 Easy                      4                 100
2                 Easy                     28                  96
3               Medium                     16                  97
4               Medium                     28                  98
...                ...                    ...                 ...
99995           Medium                      5                  95
99996             Easy                     24                  94
99997           Medium                     24                  85
99998           Medium                     28                  93
99999           Medium                      1                  92

       questions_correct  time_management_score  exam_anxiety_level  \
0                     86                    NaN                9.39
1                     86                  87.17                6.31
2                     74                  63.77                9.87
3                     77                  59.51                9.68
4                     52                  84.64               10.00
...                  ...                    ...                 ...
99995                 62                  76.13                8.36
99996                 91                  84.29                8.68
99997                 65                  62.32                9.97
99998                 81                 100.00               10.00
99999                 52                    NaN               10.00

       exam_score performance_grade pass_status performance_level
0           90.40                 A        Pass              High
1           86.21                 A        Pass              High
2           76.11                 B        Pass            Medium
3           79.74                 B        Pass            Medium
4           50.66                 D        Pass               Low
...           ...               ...         ...               ...
99995       66.46                 C        Pass            Medium
99996       96.54                 A        Pass              High
99997       74.66                 C        Pass            Medium
99998       85.85                 A        Pass              High
99999       54.40                 D        Pass               Low

[100000 rows x 44 columns]>

In [22]:
df.describe

<bound method NDFrame.describe of        student_id  age  gender education_level school_type family_income  \
0      STU_000001   20  Female     High School      Public        Middle
1      STU_000002   17    Male     High School      Public        Middle
2      STU_000003   18   Other   Undergraduate      Public        Middle
3      STU_000004   20    Male     High School      Public        Middle
4      STU_000005   16  Female     High School     Private          High
...           ...  ...     ...             ...         ...           ...
99995  STU_099996   17    Male   Undergraduate      Public  Upper-Middle
99996  STU_099997   14  Female     High School      Public  Upper-Middle
99997  STU_099998   16  Female     High School      Public  Upper-Middle
99998  STU_099999   15  Female     High School     Private          High
99999  STU_100000   18  Female   Undergraduate     Charter  Lower-Middle

      parent_education urban_rural  previous_exam_score  previous_gpa  ...  \
0                  NaN       Rural                78.36          2.95  ...
1                  NaN    Suburban                73.40          2.89  ...
2               Master       Urban                82.76          3.35  ...
3          High School    Suburban                60.61          2.57  ...
4             Bachelor    Suburban                74.79          2.84  ...
...                ...         ...                  ...           ...  ...
99995              NaN    Suburban                78.73           NaN  ...
99996         Bachelor    Suburban                75.70          2.98  ...
99997      High School    Suburban                84.69          3.27  ...
99998           Master       Rural                74.70          3.06  ...
99999              NaN       Urban                76.73          2.97  ...

       exam_difficulty  exam_preparation_days questions_attempted  \
0               Medium                     27                  95
1                 Easy                      4                 100
2                 Easy                     28                  96
3               Medium                     16                  97
4               Medium                     28                  98
...                ...                    ...                 ...
99995           Medium                      5                  95
99996             Easy                     24                  94
99997           Medium                     24                  85
99998           Medium                     28                  93
99999           Medium                      1                  92

       questions_correct  time_management_score  exam_anxiety_level  \
0                     86                    NaN                9.39
1                     86                  87.17                6.31
2                     74                  63.77                9.87
3                     77                  59.51                9.68
4                     52                  84.64               10.00
...                  ...                    ...                 ...
99995                 62                  76.13                8.36
99996                 91                  84.29                8.68
99997                 65                  62.32                9.97
99998                 81                 100.00               10.00
99999                 52                    NaN               10.00

       exam_score performance_grade pass_status performance_level
0           90.40                 A        Pass              High
1           86.21                 A        Pass              High
2           76.11                 B        Pass            Medium
3           79.74                 B        Pass            Medium
4           50.66                 D        Pass               Low
...           ...               ...         ...               ...
99995       66.46                 C        Pass            Medium
99996       96.54                 A        Pass              High
99997       74.66                 C        Pass            Medium
99998       85.85                 A        Pass              High
99999       54.40                 D        Pass               Low

[100000 rows x 44 columns]>

In [60]:
df.isnull()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,False,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False
99996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99999,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [24]:
df.isnull().sum()

student_id                       0
age                              0
gender                           0
education_level                  0
school_type                      0
family_income                    0
parent_education              6526
urban_rural                      0
previous_exam_score              0
previous_gpa                  7793
attendance_percentage         9863
assignment_completion_rate       0
class_participation              0
study_hours_per_day              0
self_study_hours                 0
private_tuition                  0
online_learning_hours            0
study_consistency                0
study_environment                0
study_method                     0
revision_frequency               0
practice_tests_completed         0
notes_quality                 8407
sleep_hours                      0
sleep_quality                 6994
daily_screen_time                0
physical_activity_hours          0
break_frequency                  0
stress_level                     0
motivation_level                 0
internet_access                  0
device_availability           2965
educational_app_usage            0
online_course_hours              0
exam_difficulty                  0
exam_preparation_days            0
questions_attempted              0
questions_correct                0
time_management_score         9613
exam_anxiety_level               0
exam_score                       0
performance_grade                0
pass_status                      0
performance_level                0
dtype: int64

In [25]:
df.dropna()

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
7,STU_000008,20,Female,Undergraduate,Private,Lower-Middle,Bachelor,Suburban,90.79,3.63,...,Easy,7,94,91,88.08,10.00,97.61,A,Pass,High
8,STU_000009,15,Male,Undergraduate,Public,Lower-Middle,Associate,Suburban,61.28,2.43,...,Hard,14,94,35,70.21,8.34,34.44,F,Fail,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,STU_099992,19,Female,Undergraduate,Public,Upper-Middle,Master,Suburban,72.32,3.05,...,Medium,3,97,63,75.44,7.32,61.12,D,Pass,Medium
99992,STU_099993,19,Female,High School,Public,Low,High School,Urban,67.13,2.37,...,Easy,29,94,65,98.67,10.00,67.74,C,Pass,Medium
99994,STU_099995,15,Male,High School,Public,Low,Associate,Urban,54.37,2.13,...,Easy,5,97,39,79.83,10.00,40.70,F,Fail,Low
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High

In [26]:
df.fillna(0)

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,0,Rural,78.36,2.95,...,Medium,27,95,86,0.00,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,0,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,STU_099996,17,Male,Undergraduate,Public,Upper-Middle,0,Suburban,78.73,0.00,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,14,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,16,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,15,Female,High School,Private,High,Master,Rural,74.70,3.06,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,18,Female,Undergraduate,Charter,Lower-Middle,0,Urban,76.73,2.97,...,Medium,1,92,52,0.00,10.00,54.40,D,Pass,Low

In [27]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df["age"]

0        20
1        17
2        18
3        20
4        16
         ..
99995    17
99996    14
99997    16
99998    15
99999    18
Name: age, Length: 100000, dtype: int64

In [31]:
df["age"].mean()

np.float64(17.00574)

In [32]:
df["age"].median()

np.float64(17.0)

In [33]:
df["age"].mode()

0    17
Name: age, dtype: int64

In [34]:
df["age"].var()

np.float64(3.9982470348703485)

In [35]:
df["age"].std()

np.float64(1.999561710693208)

In [36]:
df["age"].min()

np.int64(14)

In [37]:
df["age"].max()

np.int64(20)

In [38]:
df["age"].count()

np.int64(100000)

In [39]:
df["age"].unique()

array([20, 17, 18, 16, 15, 19, 14])

In [40]:
df["age"].nunique()

7

In [43]:
df[["age","previous_gpa"]]

       age  previous_gpa
0       20          2.95
1       17          2.89
2       18          3.35
3       20          2.57
4       16          2.84
...    ...           ...
99995   17           NaN
99996   14          2.98
99997   16          3.27
99998   15          3.06
99999   18          2.97

[100000 rows x 2 columns]

In [46]:
df[df["age"]>30]

Empty DataFrame
Columns: [student_id, age, gender, education_level, school_type, family_income, parent_education, urban_rural, previous_exam_score, previous_gpa, attendance_percentage, assignment_completion_rate, class_participation, study_hours_per_day, self_study_hours, private_tuition, online_learning_hours, study_consistency, study_environment, study_method, revision_frequency, practice_tests_completed, notes_quality, sleep_hours, sleep_quality, daily_screen_time, physical_activity_hours, break_frequency, stress_level, motivation_level, internet_access, device_availability, educational_app_usage, online_course_hours, exam_difficulty, exam_preparation_days, questions_attempted, questions_correct, time_management_score, exam_anxiety_level, exam_score, performance_grade, pass_status, performance_level]
Index: []

[0 rows x 44 columns]

In [47]:
df.sort_values("age")

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
58,STU_000059,14,Male,Undergraduate,Private,Lower-Middle,High School,Rural,67.59,2.96,...,Medium,3,95,66,100.00,9.23,72.53,C,Pass,Medium
63,STU_000064,14,Female,Undergraduate,Public,Lower-Middle,Associate,Urban,58.77,2.08,...,Hard,23,99,78,74.58,8.86,79.10,B,Pass,Medium
71314,STU_071315,14,Female,Undergraduate,Public,Lower-Middle,Master,Urban,57.96,2.41,...,Easy,21,99,66,61.86,9.14,67.94,C,Pass,Medium
71323,STU_071324,14,Male,Undergraduate,Public,Middle,High School,Suburban,81.30,3.28,...,Medium,27,88,54,79.81,10.00,64.20,D,Pass,Medium
71324,STU_071325,14,Male,High School,Private,Middle,NaN,Rural,79.58,3.17,...,Medium,17,92,79,74.55,10.00,89.13,A,Pass,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71341,STU_071342,20,Male,Undergraduate,Private,Middle,Associate,Urban,66.00,2.70,...,Hard,16,100,75,71.62,6.58,75.55,B,Pass,Medium
71340,STU_071341,20,Male,High School,Private,High,High School,Rural,63.60,2.52,...,Medium,12,93,54,80.89,10.00,56.90,D,Pass,Low
46,STU_000047,20,Female,High School,Public,Middle,Master,Rural,81.12,3.34,...,Hard,3,91,64,73.60,9.50,70.64,C,Pass,Medium
71321,STU_071322,20,Female,Undergraduate,Public,Low,Bachelor,Urban,75.34,3.17,...,Easy,28,88,78,65.48,8.15,86.81,A,Pass,High
71338,STU_071339,20,Female,Undergraduate,Private,Lower-Middle,High School,Suburban,59.23,2.44,...,Hard,16,90,42,75.44,9.97,47.87,F,Fail,Low

In [48]:
df.groupby("family_income")

In [57]:
df.drop("age",axis=1)

,student_id,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,attendance_percentage,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,81.49,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,NaN,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,100.00,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,84.91,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,88.21,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,STU_099996,Male,Undergraduate,Public,Upper-Middle,NaN,Suburban,78.73,NaN,89.67,...,Medium,5,95,62,76.13,8.36,66.46,C,Pass,Medium
99996,STU_099997,Female,High School,Public,Upper-Middle,Bachelor,Suburban,75.70,2.98,83.87,...,Easy,24,94,91,84.29,8.68,96.54,A,Pass,High
99997,STU_099998,Female,High School,Public,Upper-Middle,High School,Suburban,84.69,3.27,89.57,...,Medium,24,85,65,62.32,9.97,74.66,C,Pass,Medium
99998,STU_099999,Female,High School,Private,High,Master,Rural,74.70,3.06,92.61,...,Medium,28,93,81,100.00,10.00,85.85,A,Pass,High
99999,STU_100000,Female,Undergraduate,Charter,Lower-Middle,NaN,Urban,76.73,2.97,90.32,...,Medium,1,92,52,NaN,10.00,54.40,D,Pass,Low

In [58]:
df.groupby("previous_exam_score")

In [59]:
df.groupby("previous_exam_score")["age"].mean()

previous_exam_score
30.00     16.894737
30.05     18.000000
30.11     20.000000
30.23     17.000000
30.39     18.000000
            ...
99.96     16.500000
99.97     16.000000
99.98     17.500000
99.99     17.000000
100.00    16.975369
Name: age, Length: 6153, dtype: float64

In [61]:
df.iloc[0:5]

,student_id,age,gender,education_level,school_type,family_income,parent_education,urban_rural,previous_exam_score,previous_gpa,...,exam_difficulty,exam_preparation_days,questions_attempted,questions_correct,time_management_score,exam_anxiety_level,exam_score,performance_grade,pass_status,performance_level
0,STU_000001,20,Female,High School,Public,Middle,NaN,Rural,78.36,2.95,...,Medium,27,95,86,NaN,9.39,90.40,A,Pass,High
1,STU_000002,17,Male,High School,Public,Middle,NaN,Suburban,73.40,2.89,...,Easy,4,100,86,87.17,6.31,86.21,A,Pass,High
2,STU_000003,18,Other,Undergraduate,Public,Middle,Master,Urban,82.76,3.35,...,Easy,28,96,74,63.77,9.87,76.11,B,Pass,Medium
3,STU_000004,20,Male,High School,Public,Middle,High School,Suburban,60.61,2.57,...,Medium,16,97,77,59.51,9.68,79.74,B,Pass,Medium
4,STU_000005,16,Female,High School,Private,High,Bachelor,Suburban,74.79,2.84,...,Medium,28,98,52,84.64,10.00,50.66,D,Pass,Low

In [68]:
df["previous_gpa"]=df["previous_exam_score"]*0.10